config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
  get "about", to: "home#about"
  #resouces definit toutes les routes pour articles show edit destroy update new create index
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :articles
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 10, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :description))
    if @article.save
      flash[:notice] = "L'article a ete cree avec succes"
      #la prochaine ligne va recuperer l'article creer et lafficher
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description))
      flash[:notice] = "L'article a ete modifie avec succes"
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
end

app/controllers/articlesbackup_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destory]

  def show
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "L'article a ete cree avec succes"
      #la prochaine ligne va recuperer l'article creer et lafficher
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "L'article a ete modifie avec succes"
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_artcle
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |f| %>
  <% if @article.errors.any? %>
    <h2>The following errors prevented the article from being updated:</h2>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="row justify-content-md-center">
    <div class="col-4 mt-4 shadow rounded-3 my-form">
      <div class="mb-3">
        <%= f.label :title, for:"title", class:"form-label" %>
        <%= f.text_field :title, class:"form-control", placeholder:"Article Title" %> 
      </div>
      <div class="mb-3">
        <%= f.label :description, class:"form-label" %>
        <%= f.text_area :description, class:"form-control", rows:"6", placeholder:"Article Content ...." %>
      </div>
      <div>
        <%= f.submit class:"btn btn-outline-success my-btn" %>
      </div>
    </div> 
    <div class="text-center mt-3">
      <%= link_to "Voir tous les articles", "/articles", class: "text-dark " %>
    </div> 
  </div>
<% end %>

app/views/articles/edit.html.erb
<H1>Edit Article</H1>

<%= render 'form'%>
<!-- parcequil sont dans le meme dossier -->


<br><%= link_to "Voir tous les articles", "/articles" %>

app/views/articles/index.html.erb
<H1 class="text-center mt-4">Listing all articles</H1>


    <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-6 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
          <div class="card-header fst-italic">
            By petitdieng
          </div>
          <div class="card-body">
            <h5 class="card-title"><%=link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%=truncate(article.description, length: 100)%></p>
            <%= link_to "show", article_path(article), class:"btn btn-outline-success"%> ||
            <%= link_to "edit", edit_article_path(article),class:"btn btn-outline-primary"%> ||
            <%= link_to "Delete", article_path(article),class:"btn btn-outline-danger", data: { "turbo-method": "delete", "turbo-confirm": "Are you sure you want to delete the article?" } %>
          </div>
          <div class="card-footer text-muted">
            <small>
              Created about <%=time_ago_in_words(article.created_at)%> | Updated about <%=time_ago_in_words(article.updated_at)%> 
            </small>
          </div>
        </div>
      </div>
    </div>
    <% end %>

  <%= link_to "Creer un article", "/articles/new" %>
  <br><%= link_to "Home page", root_path %>

app/views/articles/new.html.erb
<H1 class="text-center mt-3">Create a new article</H1>

<%=render 'form'%>

app/views/articles/show.html.erb
<H1>Details Article</H1>

<H3>Article numero <%=@article.id%></H3>

Titre:    <%=@article.title%><br>
Description:    <%=@article.title%>

<br><%= link_to "Edit", edit_article_path(@article)%>||<%= link_to "Delete", article_path(@article), data: { "turbo-method": "delete", "turbo-confirm": "Are you sure you want to delete the article?" }%>
<br><%= link_to "Creer un article", "/articles/new" %>
<br><%= link_to "Voir tous les articles", "/articles" %>
<br><%= link_to "Home page", root_path %>

app/views/home/about.html.erb
<H1>This is the About Page</H1>

<br><%= link_to "Home page", root_path %>
<br><%= link_to "Voir tous les articles", articles_path %>

app/views/home/index.html.erb
<div id="page-content">
  <div class="container rounded"id="home-container">
    <div class="jumbotron text-center">
        <h1 class="display-4">Hello, world!</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-outline-success btn-lg" href="#" role="button">Sign up</a>
      </div>
</div>

</div>

<br><%= link_to "Voir tous les articles", articles_path %>
<br><%= link_to "A propos", "/about" %>

app/views/layouts/_footer.html.erb
    <footer class="bg-dark text-center text-white footer " style="background-color: rgba(0, 0, 0, 0.948)"";>
    <div class="footer-div">
      <div class="text-center p-3">
        © 2024 PetitDieng Copyright:
        <a class="text-white" href="https://petitdieng.com/">link to me</a>
      </div>
      <div>
        <!-- Facebook -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
          <i class="fab fa-facebook-f"></i>
      </a>
  
      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
          <i class="fab fa-twitter"></i>
      </a>
  
      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"> 
          <i class="fab fa-google"></i>
      </a>
  
      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
          <i class="fab fa-instagram"></i>
      </a>
  
      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
          <i class="fab fa-linkedin-in"></i>
      </a>
  
      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
          <i class="fab fa-github"></i>
      </a>
      </div>
    </div>
  </footer>
    

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
      <%=msg%>
    <%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <%= link_to "Beta-Blog", root_path, class:"navbar-brand", id:"logo" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Articles", articles_path, class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "custom", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%=render 'layouts/navbar'%>
    <%=render 'layouts/messages'%>
    <%= yield %>
    <%=render 'layouts/footer'%>
  </body>
</html>